In [1]:
print("Hello World!")

Hello World!


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
print(np.__version__)

2.3.5


In [5]:
l1 = [1, 2, 3, 4, 5]
#print(l1) This is only list 
l1

[1, 2, 3, 4, 5]

In [6]:
x=np.array(l1)
print(x) # this is numpy array

[1 2 3 4 5]


In [7]:
#Create a 1D array
x= np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


1) find the difference between list and numpy array.

In [8]:
x=np.random.rand(5)
print(x)

[0.4585643  0.33024614 0.83848786 0.91302274 0.92227809]


In [9]:
x=np.random.randint(5,15,3)
print(x)

[13  7  7]


In [10]:
#2D array
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
y=np.random.rand(3,4)
print(y)

[[8.97624160e-01 7.38058080e-01 6.88540309e-01 5.30428688e-01]
 [8.36540439e-01 8.79787966e-01 8.07336381e-01 8.36632654e-01]
 [6.47649487e-01 2.32953066e-04 8.10924249e-01 5.77285875e-01]]


In [12]:
y=np.random.randint(5,16,(3,3))
print(y)

[[ 6 14  5]
 [12 13  5]
 [14 10  5]]


In [13]:
#3D array
z=np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])
print(z)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]


In [14]:
a=np.zeros(((3,4)),dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [15]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
a=np.full((5,5),7)
a

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [17]:
a=np.eye(4,5,dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [18]:
print("shape of array:",a.shape)

shape of array: (4, 5)


In [19]:
z.ndim

4

In [20]:
a.size

20

In [21]:
a.dtype

dtype('int64')

In [22]:
z.min()

np.int64(1)

In [23]:
z.max()

np.int64(12)

In [24]:
z.sum()

np.int64(78)

In [25]:
a.argmin()

np.int64(1)

In [26]:
x.argmax()

np.int64(0)

In [27]:
v=np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])
print(v)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]


In [28]:
e = np.array([[12,13,14],[15,16,17],[18,19,20]])
print (e)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


In [29]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])
c=a+b
d=a-b
e=a*b

In [30]:
print(c)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


indexing is the process of accesing the single element from a sequence using its position or index,it retrives a single element of specific position

indexing is the process of accesing the single element from a sequence using its position or index,it retrives a single element of specific position

## Give  A Diffrence Beetween indexing and Sclicing

# indexing  

In [31]:
arr = [10, 45, 23, 89, 12, 89]

max_value = max(arr)
location = arr.index(max_value)

print("Maximum value:", max_value)
print("Location (index):", location)


Maximum value: 89
Location (index): 3


indexing is used to access elements 
Slicing refer to the process of extracting a portion os an array or a subarry. it allows you to Access specific elements or ranges of elements in a Numpy array

In [32]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
x[-2:,1:]
x[1:3,0:2]
x[::2,::2]

array([[1, 3],
       [7, 9]])

In [34]:
y

array([[ 6, 14,  5],
       [12, 13,  5],
       [14, 10,  5]], dtype=int32)

In [35]:
y

array([[ 6, 14,  5],
       [12, 13,  5],
       [14, 10,  5]], dtype=int32)

In [36]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
x[2:5]

array([[7, 8, 9]])

In [38]:
x[5:]

array([], shape=(0, 3), dtype=int64)

In [39]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
x[:] = 200

In [41]:
np.flip(x)

array([[200, 200, 200],
       [200, 200, 200],
       [200, 200, 200]])

Tutorial : 2 - Explore Pandas library to analyze  and manipulate data.

In [42]:
#Import numPy and Pandas libraries
#install pandas before running the code
#pip install pandas
import pandas as pd

pand is an open-source library for real world data analysis in python. it is built on top of numpy

using pandas, data can be claned, transformed, manipulated, and analyzed

To get started with Pandas, Numpy and Pandas needs to be imported

The basic data structures of pandas are series and dataFrame.

1. Series object Series is a one dimensional labeled array. it support different data type like, integer, float, strig ect..

2. dataFrame

A dataframe in pandas is a two-dimensional, tabular data structure similar to a spreadsheet or sql table.

it consists of row and coloums, where:

coloumns: Represent



Row :

Index : Labels for rows, which can be integers other types

In [43]:
s1 = pd.Series([10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [44]:
s2 = pd.Series([10,20,30,40,50], index=['A','B','C','D','E'])
s2

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [45]:
s1.values


array([10, 20, 30, 40, 50])

In [46]:
s2.values

array([10, 20, 30, 40, 50])

In [47]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [48]:
s2.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [49]:
data = [{'Name' : 'Mihir', 'Marks' : 28},
        {'Name' : 'Alice', 'Marks' : 27},
        {'Name' : 'Bob', 'Marks' : 30},
        {'Name' : 'Charlie', 'Marks' : 35}]
f1 = pd.DataFrame(data)
f1

Name  Marks
0    Mihir     28
1    Alice     27
2      Bob     30
3  Charlie     35

In [50]:
data

[{'Name': 'Mihir', 'Marks': 28},
 {'Name': 'Alice', 'Marks': 27},
 {'Name': 'Bob', 'Marks': 30},
 {'Name': 'Charlie', 'Marks': 35}]

In [51]:
print(f1)

      Name  Marks
0    Mihir     28
1    Alice     27
2      Bob     30
3  Charlie     35


In [52]:
type(f1)

pandas.core.frame.DataFrame

In [53]:
type(data)

list

In [54]:
data = pd.read_excel("Book1.xlsx")
data

Name Branch Division
0       Mihir     CE        B
1       Rahul     CE        A
2      Hardik     CE        B
3       Dhiaj     CE        B
4      Arayan     IT        A
5       Nihar     CE        A
6   Amit          IT        A
7   Rohan         IT        B
8    Kunal        CE        A
9   Sahil         CE        C
10  Yash          CE        C
11  Dev           IT        A

In [55]:
data = pd.read_csv("Iris.csv")

In [56]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [57]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [58]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [59]:
data.isna()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2    False          False         False          False         False    False
3    False          False         False          False         False    False
4    False          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
145  False          False         False          False         False    False
146  False          False         False          False         False    False
147  False          False         False          False         False    False
148  False          False         False          False         False    False
149  False          False         False          False         False    False

[150 rows x 6 columns]

In [60]:
data.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [61]:
cat = data['Species'].unique()

In [62]:
cat

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [63]:
data.replace("Iris-setosa", "Setosa", inplace=True)

In [64]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0            Setosa  
1            Setosa  
2            Setosa  
3            Setosa  
4            Setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [65]:
cat

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [66]:
data.replace("Iris-virginica", "Virginica", inplace=True)

In [67]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm    Species
0      1            5.1           3.5            1.4           0.2     Setosa
1      2            4.9           3.0            1.4           0.2     Setosa
2      3            4.7           3.2            1.3           0.2     Setosa
3      4            4.6           3.1            1.5           0.2     Setosa
4      5            5.0           3.6            1.4           0.2     Setosa
..   ...            ...           ...            ...           ...        ...
145  146            6.7           3.0            5.2           2.3  Virginica
146  147            6.3           2.5            5.0           1.9  Virginica
147  148            6.5           3.0            5.2           2.0  Virginica
148  149            6.2           3.4            5.4           2.3  Virginica
149  150            5.9           3.0            5.1           1.8  Virginica

[150 rows x 6 columns]

In [68]:
data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [69]:
data[['SepalLengthCm']].head(10)

SepalLengthCm
0            5.1
1            4.9
2            4.7
3            4.6
4            5.0
5            5.4
6            4.6
7            5.0
8            4.4
9            4.9

In [70]:
data[['SepalLengthCm', 'SepalWidthCm']].head(10)

SepalLengthCm  SepalWidthCm
0            5.1           3.5
1            4.9           3.0
2            4.7           3.2
3            4.6           3.1
4            5.0           3.6
5            5.4           3.9
6            4.6           3.4
7            5.0           3.4
8            4.4           2.9
9            4.9           3.1

In [71]:
data[['PetalLengthCm', 'PetalWidthCm']].head(10)

PetalLengthCm  PetalWidthCm
0            1.4           0.2
1            1.4           0.2
2            1.3           0.2
3            1.5           0.2
4            1.4           0.2
5            1.7           0.4
6            1.4           0.3
7            1.5           0.2
8            1.4           0.2
9            1.5           0.1

In [75]:
def yes_no(SepalLengthCm):
    return 'Yes' if SepalLengthCm > 5.0 else 'No'

data['Result'] = data['SepalLengthCm'].apply(yes_no)


In [78]:
data.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species', 'Result'],
      dtype='object')

In [79]:
data.iloc[51:56]


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
51  52            6.4           3.2            4.5           1.5   
52  53            6.9           3.1            4.9           1.5   
53  54            5.5           2.3            4.0           1.3   
54  55            6.5           2.8            4.6           1.5   
55  56            5.7           2.8            4.5           1.3   

            Species Result  
51  Iris-versicolor    Yes  
52  Iris-versicolor    Yes  
53  Iris-versicolor    Yes  
54  Iris-versicolor    Yes  
55  Iris-versicolor    Yes

In [80]:
data.iloc[51:56, 2:5]

SepalWidthCm  PetalLengthCm  PetalWidthCm
51           3.2            4.5           1.5
52           3.1            4.9           1.5
53           2.3            4.0           1.3
54           2.8            4.6           1.5
55           2.8            4.5           1.3

In [82]:
data[data['PetalLengthCm'] > 5]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
83    84            6.0           2.7            5.1           1.6   
100  101            6.3           3.3            6.0           2.5   
101  102            5.8           2.7            5.1           1.9   
102  103            7.1           3.0            5.9           2.1   
103  104            6.3           2.9            5.6           1.8   
104  105            6.5           3.0            5.8           2.2   
105  106            7.6           3.0            6.6           2.1   
107  108            7.3           2.9            6.3           1.8   
108  109            6.7           2.5            5.8           1.8   
109  110            7.2           3.6            6.1           2.5   
110  111            6.5           3.2            5.1           2.0   
111  112            6.4           2.7            5.3           1.9   
112  113            6.8           3.0            5.5           2.1   
114  115            5.8           2.8            5.1           2.4   
115  116            6.4           3.2            5.3           2.3   
116  117            6.5           3.0            5.5           1.8   
117  118            7.7           3.8            6.7           2.2   
118  119            7.7           2.6            6.9           2.3   
120  121            6.9           3.2            5.7           2.3   
122  123            7.7           2.8            6.7           2.0   
124  125            6.7           3.3            5.7           2.1   
125  126            7.2           3.2            6.0           1.8   
128  129            6.4           2.8            5.6           2.1   
129  130            7.2           3.0            5.8           1.6   
130  131            7.4           2.8            6.1           1.9   
131  132            7.9           3.8            6.4           2.0   
132  133            6.4           2.8            5.6           2.2   
133  134            6.3           2.8            5.1           1.5   
134  135            6.1           2.6            5.6           1.4   
135  136            7.7           3.0            6.1           2.3   
136  137            6.3           3.4            5.6           2.4   
137  138            6.4           3.1            5.5           1.8   
139  140            6.9           3.1            5.4           2.1   
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146            6.7           3.0            5.2           2.3   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

             Species Result  
83   Iris-versicolor    Yes  
100        Virginica    Yes  
101        Virginica    Yes  
102        Virginica    Yes  
103        Virginica    Yes  
104        Virginica    Yes  
105        Virginica    Yes  
107        Virginica    Yes  
108        Virginica    Yes  
109        Virginica    Yes  
110        Virginica    Yes  
111        Virginica    Yes  
112        Virginica    Yes  
114        Virginica    Yes  
115        Virginica    Yes  
116        Virginica    Yes  
117        Virginica    Yes  
118        Virginica    Yes  
120        Virginica    Yes  
122        Virginica    Yes  
124        Virginica    Yes  
125        Virginica    Yes  
128        Virginica    Yes  
129        Virginica    Yes  
130        Virginica    Yes  
131        Virginica    Yes  
132        Virginica    Yes  
133        Virginica    Yes  
134        Virginica    Yes  
135        Virginica    Yes  
136        Virginica    Yes  
137        Virginica    Yes  
139  

In [83]:
data[(data['PetalLengthCm'] > 6) & (data['Species'] == 'Virginica')]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm    Species  \
105  106            7.6           3.0            6.6           2.1  Virginica   
107  108            7.3           2.9            6.3           1.8  Virginica   
109  110            7.2           3.6            6.1           2.5  Virginica   
117  118            7.7           3.8            6.7           2.2  Virginica   
118  119            7.7           2.6            6.9           2.3  Virginica   
122  123            7.7           2.8            6.7           2.0  Virginica   
130  131            7.4           2.8            6.1           1.9  Virginica   
131  132            7.9           3.8            6.4           2.0  Virginica   
135  136            7.7           3.0            6.1           2.3  Virginica   

    Result  
105    Yes  
107    Yes  
109    Yes  
117    Yes  
118    Yes  
122    Yes  
130    Yes  
131    Yes  
135    Yes

In [14]:
data = pd.read_csv("Iris.csv")

In [15]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [16]:
data.duplicated

<bound method DataFrame.duplicated of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iri

In [17]:
data.duplicated().sum()

np.int64(0)

In [20]:
student = pd.read_csv('data/student_info.csv')

In [21]:
student.columns

Index(['study_hours', 'student_marks'], dtype='object')

In [22]:
student.head

<bound method NDFrame.head of      study_hours  student_marks
0           6.83          78.50
1           6.56          76.74
2            NaN          78.68
3           5.67          71.82
4           8.67          84.19
..           ...            ...
195         7.53          81.67
196         8.56          84.68
197         8.94          86.75
198         6.60          78.05
199         8.35          83.50

[200 rows x 2 columns]>

In [23]:
student.tail

<bound method NDFrame.tail of      study_hours  student_marks
0           6.83          78.50
1           6.56          76.74
2            NaN          78.68
3           5.67          71.82
4           8.67          84.19
..           ...            ...
195         7.53          81.67
196         8.56          84.68
197         8.94          86.75
198         6.60          78.05
199         8.35          83.50

[200 rows x 2 columns]>

In [24]:
student.notnull

<bound method DataFrame.notnull of      study_hours  student_marks
0           6.83          78.50
1           6.56          76.74
2            NaN          78.68
3           5.67          71.82
4           8.67          84.19
..           ...            ...
195         7.53          81.67
196         8.56          84.68
197         8.94          86.75
198         6.60          78.05
199         8.35          83.50

[200 rows x 2 columns]>

In [25]:
student.isna().sum()

study_hours      5
student_marks    0
dtype: int64

In [26]:
student['study_hours']=student['study_hours'].fillna(student['study_hours'].mean())

In [27]:
student.isna().sum()

study_hours      0
student_marks    0
dtype: int64

In [28]:
pip install ucimlrepo


   -------------------- ------------------- 1/2 [ucimlrepo]
   ---------------------------------------- 2/2 [ucimlrepo]

Note: you may need to restart the kernel to use updated packages.


In [32]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
adult = fetch_ucirepo(id=2) 
  
# data (as pandas dataframes) 
X = adult.data.features 
y = adult.data.targets 
  
# metadata 
print(adult.metadata) 
  
# variable information 
print(adult.variables) 


{'uci_id': 2, 'name': 'Adult', 'repository_url': 'https://archive.ics.uci.edu/dataset/2/adult', 'data_url': 'https://archive.ics.uci.edu/static/public/2/data.csv', 'abstract': 'Predict whether annual income of an individual exceeds $50K/yr based on census data. Also known as "Census Income" dataset. ', 'area': 'Social Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 48842, 'num_features': 14, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Income', 'Education Level', 'Other', 'Race', 'Sex'], 'target_col': ['income'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1996, 'last_updated': 'Tue Sep 24 2024', 'dataset_doi': '10.24432/C5XW20', 'creators': ['Barry Becker', 'Ronny Kohavi'], 'intro_paper': None, 'additional_info': {'summary': "Extraction was done by Barry Becker from the 1994 Census database.  A set of reasonably clean records was extracted using the fol

In [34]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             48842 non-null  int64 
 1   workclass       47879 non-null  object
 2   fnlwgt          48842 non-null  int64 
 3   education       48842 non-null  object
 4   education-num   48842 non-null  int64 
 5   marital-status  48842 non-null  object
 6   occupation      47876 non-null  object
 7   relationship    48842 non-null  object
 8   race            48842 non-null  object
 9   sex             48842 non-null  object
 10  capital-gain    48842 non-null  int64 
 11  capital-loss    48842 non-null  int64 
 12  hours-per-week  48842 non-null  int64 
 13  native-country  48568 non-null  object
dtypes: int64(6), object(8)
memory usage: 5.2+ MB


In [36]:
X.isna().sum()

age                 0
workclass         963
fnlwgt              0
education           0
education-num       0
marital-status      0
occupation        966
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
hours-per-week      0
native-country    274
dtype: int64

In [35]:
X['workclass'].unique()

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', '?', 'Self-emp-inc', 'Without-pay', 'Never-worked',
       nan], dtype=object)